apiVersion: v1
kind: ConfigMap
metadata:
  name: corebanking-ledger-config
  namespace: corebanking
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
  KAFKA_CONSUMER_GROUP: "corebanking-ledger"
  SPRING_PROFILES_ACTIVE: "prod"
